FROM ubuntu:16.04

RUN apt update -q && apt install -y \
    ca-certificates \
    build-essential \
    libssl-dev \
    python \
    python-dev \
    python-setuptools

RUN easy_install pip && pip --version

RUN pip install --no-cache ansible && ansible --version

RUN mkdir -p /etc/ansible && echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts
